name: staditic_trading_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  animate_do: ^3.3.3
  dio: ^5.4.1
  equatable: ^2.0.5
  fl_chart: ^0.60.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_riverpod: ^2.4.10
  formz: ^0.6.1
  go_router: ^13.2.0
  google_fonts: ^6.1.0
  intl: ^0.18.1
  shared_preferences: ^2.2.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/loaders/
    - assets/images/
    - google_fonts/montserrat_alternates/

  fonts:
    - family: Gotham-Light
      fonts:
        - asset: assets/fonts/Gotham-Light.otf

    - family: Gotham-Black
      fonts:
        - asset: assets/fonts/Gotham-Black.otf

    - family: Gotham-Medium
      fonts:
        - asset: assets/fonts/Gotham-Medium.otf

    - family: Gotham-Book
      fonts:
        - asset: assets/fonts/Gotham-Book.otf

    - family: Gotham-Bold
      fonts:
        - asset: assets/fonts/Gotham-Bold.otf